### ISSUE TITLE
Crash when PartialSheet used on a view presented as "sheet"

### ISSUE THREAD

**Issue by SergejLogis** [AndreaMiotto/PartialSheet#79] opened 2020-11-13 08:03 UTC
**Issue:** We have hit a crash when using PartialSheet in a screen presented as a `sheet`. 

**Evinronment:** We do setup `PartialSheet` according to documentation - registering instance of `PartialSheetManager` as an environment object on a `RootView` in `SceneDelegate`. It does work as intended for the tabs and for the pushed screens. But when we try to use it in a `sheet` we got a lot of crashes at a different times. E.g. app may crash after dismissing a sheet or after multiple taps on a `TextEditor` view, even if partial sheet wasn't presented at all.
```
let contentView = RootScreen(dependencies: environment.container)
    .environmentObject(PartialSheetManager())

if let windowScene = scene as? UIWindowScene {
    let window = UIWindow(windowScene: windowScene)
    window.rootViewController = UIHostingController(rootView: contentView)
    self.window = window
    window.makeKeyAndVisible()
}
```
The crash happens because at some point when SwiftUI rebuilds `body` of a screen there is no `PartialSheetManager` available in environment anymore.
<img width="1043" alt="PartialSheet crash" src="https://user-images.githubusercontent.com/32644729/99042066-c1b23000-2594-11eb-8471-2fad6890c868.png">

**Workaround:** After ~3 hours of trial-and-error we finally were able to find a working solution: re-adding shared instance of `PartialSheetManager` on **every** view via a custom modifier:
```
extension View {
    @ViewBuilder func addPartialSheetManager() -> some View {
        // Executes closure if object is not `nil`.
        modifier(for: SceneDelegate.current?.partialSheetManager) { view, manager in
            view.environmentObject(manager)
        }
    }
}
```
And then in the view presented as a `sheet`:
```
struct SheetScreen: View {
    @State private var isPartialSheetShown = false

    var body: some View {
        ZStack {
            VStack {
                // SCREEN CONTENT
            }
            .addPartialSheet()
            .partialSheet(isPresented: $isPartialSheetShown) {
                // PARTIAL SHEET CONTENT
            }
        }
        .addPartialSheetManager()
    }
}
```

**Conclusion:** Not sure if this is the issue with PartialSheet library or with SwiftUI itself. It would be great to get some insight from the creator of this amazing library. 🤓🙇‍♂️

Thank you.

**Comment by styrken** [comment] 2020-11-23 08:49
Hello @SergejLogis, thank you for the workaround. We will have to try and reproduce it and see what goes on.

**Comment by SergejLogis** [comment] 2020-12-02 15:48
We just hit another issue with PartialSheet when used in view persented as a `sheet`, but this time it only happens on iOS 13.
<img width="749" alt="Screenshot 2020-12-02 at 17 45 07" src="https://user-images.githubusercontent.com/32644729/100895589-6786f980-34c6-11eb-8fde-2eb741982cd6.png">

**Crash log:**
> CoreSimulator 732.18.0.2 - Device: iPhone 11 Pro (25F10771-4730-4A1D-8EFB-3FCDBEE65592) - Runtime: iOS 13.7 (17H22) - DeviceType: iPhone 11 Pro
AttributeGraph precondition failure: invalid input index: 2.

This time we weren't able to find a workaround, though... 😐

**Comment by styrken** [comment] 2021-02-04 18:58
I think it kind of makes sense that you have to add the PartialSheet manager again as environmentObject() for presented views, since as I undertand it is a new "context" in SwiftUI and environmental objects is not passed along to modals. It might be fixed on iOS 14 but I am not sure.

**Comment by styrken** [comment] 2021-02-04 18:59
Regaring the iOS 13 issue - is ```proxy``` not set?

**Comment by SergejLogis** [comment] 2021-02-05 07:44
I don't have anything against passing `PartialSheetManager` down the line. The issue is that crash happens _on dismiss_, when we don't have any control over the environment anymore. I have debugged the code, and I see that `PartialSheetViewModifier` tries to update its components during dismissal (since the state has changed), but `@EnvironmentObject` is not available anymore and BOOM! 💥 - we have a crash. If it would just silently return whenever `PartialSheetManager` is not available - everything would be just fine. However, `@EnvironmentObject` cannot be `nil`. In theory that issue could be solved by using `@Environment` instead since it will have the default value and that value can be `nil`. In such cases whenever there is no `PartialSheetManager` available in the environment - no processing is done and nothing will blow up. 🤓

**Comment by styrken** [comment] 2021-02-06 20:51
Okay i see, thanks for the clarification. I think the change would be too major for the library at the moment but I think we have to do something to support this issue. 

I am kind of surprise that it is not possible to mark an the ```@EnvironmentObject``` as optional so we could check if it was there or not. Seems like a missing feature in SwiftUI (?) and sadly introduces bugs when we cannot trust if the value is there.

**Comment by AndreaMiotto** [comment] 2021-09-20 13:58
I solved this problem in the version 3 of the project, that is going to be released as soon as Apple publish iOS 15.
You can see the PR in progress at: #128

**Closed by AndreaMiotto** 2021-09-20 13:58 UTC
Labels: help wanted
